global:
  resolve_timeout: 5m

route:
  receiver: "default-receiver"
  group_by: ["alertname", "service"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h

  routes:
    - match:
        severity: critical
      receiver: "discord-receiver"
      group_interval: 1m
      repeat_interval: 30m

    - match:
        severity: warning
      receiver: "default-receiver"

receivers:
  - name: "discord-receiver"
    webhook_configs:
      - url: "https://discord.com/api/webhooks/1295445227766808668/Qs7XDL8skhqFuqHP8lJz91qkJfKFPF1IpzqX9Sxy3AqfkR0ONji8x0rKSeutSwuF46XT"
        send_resolved: true

  - name: "default-receiver"
    webhook_configs:
      - url: "https://discord.com/api/webhooks/1295445227766808668/Qs7XDL8skhqFuqHP8lJz91qkJfKFPF1IpzqX9Sxy3AqfkR0ONji8x0rKSeutSwuF46XT"
        send_resolved: true

inhibit_rules:
  - source_match:
      severity: critical
    target_match:
      severity: warning
    equal: ["alertname", "service"]
