---
- name: Include vars.yml
  include_vars: vars/vars.yml

- name: 1. Update apt cache
  apt:
    update_cache: yes

- name: 2. Install Java JDK11
  apt:
    name: openjdk-11-jdk
    state: present

- name: 3. Install Tomcat9
  apt:
    name: tomcat9
    state: present

- name: 4. Create directory for application
  file:
    path: /var/lib/tomcat9/webapps
    state: directory
    owner: tomcat
    group: tomcat
    mode: '0755'

- name: 5. Remove existing ROOT directory
  file:
    path: /var/lib/tomcat9/webapps/ROOT
    state: absent

- name: 6. Copy .env file to Tomcat
  copy:
    src: "{{ playbook_dir }}/roles/backend/templates/.env.j2"
    dest: /var/lib/tomcat9/.env
    owner: tomcat
    group: tomcat
    mode: '0644'

- name: 7. Copy WAR file to Tomcat
  copy:
     src: "{{ playbook_dir }}/roles/backend/files/ROOT.war"
     dest: /var/lib/tomcat9/webapps/
     owner: tomcat
     group: tomcat
     mode: '0644'
  notify: Restart Tomcat

- name: 8. Create directory for unpacked WAR
  file:
    path: /var/lib/tomcat9/webapps/ROOT/
    state: directory
    owner: tomcat
    group: tomcat
    mode: '0755' 

- name: 9. Unpack WAR file to Tomcat
  unarchive:
    src: /var/lib/tomcat9/webapps/ROOT.war
    dest: /var/lib/tomcat9/webapps/ROOT/
    remote_src: yes 
  notify: Restart Tomcat

- name: 10. Include properties tasks
  include_tasks: properties.yml
  
- name: 11. Ensure that Tomcat is started
  service:
    name: tomcat9
    state: started
    enabled: true
  notify: Restart Tomcat

- name: Set API base URL
  set_fact:
    REACT_APP_API_BASE_URL: "http://{{ backend_ip }}:8080"
