version: '3.8'

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: annasever/class_schedule/backend:latest 
    container_name: backend    
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - mongo
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile 
    image: annasever/class_schedule/frontend:latest
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
        
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db        

volumes:
  postgres_data:
  redis_data:
  mongo_data:
