plugin: aws_ec2
aws_access_key: "{{ lookup('file', 'aws_creds.yml') | from_yaml | json_query('aws_access_key') }}"
aws_secret_key: "{{ lookup('file', 'aws_creds.yml') | from_yaml | json_query('aws_secret_key') }}"

regions:
  - eu-central-1

filters:
  instance-state-name: running
  tag:Name:
    - prometheus
    - databases
    - backend
    - frontend

keyed_groups:
  - key: tags
    prefix: tag
  - prefix: instance_type
    key: instance_type
  - key: placement.region
    prefix: aws_region
  - key: tags.NodeType
    prefix: node_exporter

compose:
  ansible_host: public_ip_address
  ansible_user: ubuntu
  ansible_ssh_private_key_file: ~/.ssh/vasilenko.pem
