---
- hosts: tag_Name_prometheus
  become: true
  remote_user: ubuntu
  roles:
    - alertmanager
    - node_exporter

- hosts: tag_Name_databases
  become: true
  remote_user: ubuntu
  roles:
    - node_exporter

- hosts: tag_Name_backend
  become: true
  remote_user: ubuntu
  roles:
    - node_exporter

- hosts: tag_Name_frontend
  become: true
  remote_user: ubuntu
  roles:
    - node_exporter

- hosts: tag_Name_prometheus
  become: true
  remote_user: ubuntu
  roles:
    - prometheus

- hosts: tag_Name_prometheus
  become: true
  remote_user: ubuntu
  roles:
    - grafana
