---
- name: Include vars.yml
  include_vars: vars/vars.yml

- name: 1. Install Redis
  apt:
    name: redis-server
    state: present

- name: 2. Ensure Redis is running
  service:
    name: redis-server
    state: started
    enabled: yes

- name: 3. Configure Redis
  template:
    src: "redis.conf.j2"
    dest: "{{ redis_conf_path }}"
    owner: redis
    group: redis
    mode: "0644"

- name: 4. Restart Redis
  service:
    name: redis-server
    state: restarted




# - name: Include vars.yml
#   include_vars: vars/vars.yml

# - name: Update the apt cache
#   apt:
#     update_cache: yes

# - name: 1. Define redis_package.
#   set_fact:
#     redis_package: "{{ redis_package }}"
#   when: redis_package is not defined

# - name: 2. Ensure Redis configuration dir exists.
#   file:
#     path: "{{ redis_conf_path | dirname }}"
#     state: directory
#     mode: "{{ redis_conf_dir_mode }}"

# - name: 3. Ensure Redis is configured.
#   template:
#     src: redis.conf.j2
#     dest: "{{ redis_conf_path }}"
#     mode: "{{ redis_conf_mode }}"
#   notify: restart redis

# - name: 4. Ensure Redis is installed.
#   apt:
#     name: "{{ redis_package }}"
#     state: present

# - name: Ensure Redis configuration dir exists.
#   file:
#     path: "{{ redis_conf_path | dirname }}"
#     state: directory
#     mode: "{{ redis_conf_dir_mode }}"

# - name: Ensure Redis is configured.
#   template:
#     src: redis.conf.j2
#     dest: "{{ redis_conf_path }}"
#     mode: "{{ redis_conf_mode }}"
#   notify: restart redis