---
- name: Include vars.yml
  include_vars: vars/vars.yml

- name: 1. Update APT package cache
  apt:
    update_cache: yes

- name: 2. Install Redis
  apt:
    name: redis-server
    state: present

# - name: 3. Ensure Redis is running
#   service:
#     name: redis-server
#     state: started
#     enabled: yes

- name: 4. Configure Redis
  template:
    src: "redis.conf.j2"
    dest: "{{ redis_conf_path }}"
    owner: redis
    group: redis
    mode: "0644"
#  notify: Restart Redis