---
- name: 1. Install Redis
  apt:
    name: redis-server
    state: present

- name: 2. Ensure Redis is running
  service:
    name: redis-server
    state: started
    enabled: yes

- name: 3. Configure Redis
  copy:
    src: "/home/ubuntu/internship_project/ansible_project/roles/databases/files/redis.conf"
    dest: /etc/redis/redis.conf
    owner: redis
    group: redis
    mode: "0644"

- name: 4. Restart Redis
  service:
    name: redis-server
    state: restarted
