apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  POSTGRES_DB: "database"
  POSTGRES_USER: "user"
  POSTGRES_PASSWORD: "password"
  POSTGRES_PORT: "5432"
  POSTGRES_HOST: "postgres"
  MONGO_INITDB_DATABASE: "schedules"
  REDIS_PORT: "6379"
