---
__postgresql_version: "14"
__postgresql_data_dir: "/var/lib/postgresql/{{ __postgresql_version }}/main"
__postgresql_bin_path: "/usr/lib/postgresql/{{ __postgresql_version }}/bin"
__postgresql_config_path: "/etc/postgresql/{{ __postgresql_version }}/main"
__postgresql_daemon: postgresql
__postgresql_packages:
  - postgresql
  - postgresql-contrib
  - libpq-dev
# postgresql_python_library: python3-psycopg2

# postgresql_database: my_database
db_backup_filename: "2024-08-19.dump"
# postgresql_password: password
# postgresql_data_dir1: "/var/lib/postgresql/data"

postgresql_user: "postgres"
postgresql_group: "postgres"
postgresql_password: "password" # Consider using Ansible Vault for sensitive data
postgresql_data_dir1: "/var/lib/postgresql/data"
postgresql_effective_log_dir: "/var/log/postgresql"
postgresql_daemon: "postgresql"
postgresql_python_library: "python3-psycopg2"
postgresql_packages:
  - "postgresql"
  - "postgresql-contrib"
postgresql_locales:
  - "en_US.UTF-8"
postgresql_global_config_options:
  - { option: "listen_addresses", value: "*", state: "present" }
postgresql_hba_entries: [] # Add your entries as needed
postgresql_unix_socket_directories:
  - "/var/run/postgresql"
postgresql_service_state: "started"
postgresql_service_enabled: true
postgresql_bin_path: "/usr/lib/postgresql/14/bin"
postgresql_config_path: "/etc/postgresql/14/main"
