---
# RHEL/CentOS only. Set a repository to use for PostgreSQL installation.
postgresql_enablerepo: ""

# Set postgresql state when configuration changes are made. Recommended values:
# `restarted` or `reloaded`
postgresql_restarted_state: "restarted"

postgresql_python_library: python-psycopg2
postgresql_user: postgres
postgresql_group: postgres
postgresql_database: mydatabase

# `md5` or `scram-sha-256` (https://www.postgresql.org/docs/10/auth-methods.html)
postgresql_auth_method: "{{ ansible_fips  | ternary('scram-sha-256', 'md5') }}"

postgresql_unix_socket_directories:
  - /var/run/postgresql

postgresql_service_state: started
postgresql_service_enabled: true

# Global configuration options that will be set in postgresql.conf.
postgresql_global_config_options:
  - option: unix_socket_directories
    value: '{{ postgresql_unix_socket_directories | join(",") }}'
  - option: log_directory
    value: 'log'

# Host based authentication (hba) entries to be added to the pg_hba.conf. This
# variable's defaults reflect the defaults that come with a fresh installation.
postgresql_hba_entries:
  - {type: local, database: all, user: postgres, auth_method: trust}
  - {type: local, database: all, user: all, auth_method: trust}
  - {type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: "{{ postgresql_auth_method }}"}
  - {type: host, database: all, user: all, address: '::1/128', auth_method: "{{ postgresql_auth_method }}"}


# Debian only. Used to generate the locales used by PostgreSQL databases.
postgresql_locales:
  - 'en_US.UTF-8'

# Databases to ensure exist.
postgresql_databases: 
- name: "{{ postgresql_database }}"
  login_host: localhost
  login_port: 5432
  login_password: password
  login_user: "{{ postgresql_user }}"
  login_unix_socket: /var/run/postgresql
  owner:  "{{ postgresql_user }}"
  state:  present

# Users to ensure exist.
postgresql_users: 
- name: postgres
  password: password
  priv: "{{ postgresql_database }}:ALL"
  db: "{{ postgresql_database }}"
  login_host: localhost
  login_password: password
  login_user: "{{ postgresql_user }}"
  login_unix_socket: /var/run/postgresql
  state: present

# Whether to output user data when managing users.
postgres_users_no_log: true