---
postgres_user: "postgres"
postgres_database: "my_database"
postgres_port: 5432
postgres_host: "{{ hostvars['tag_Name_databases'].ansible_host }}"
postgresql_password: "password"

mongo_initdb_database: "schedules"
redis_port: 6379

backend_ip: "{{ hostvars['tag_Name_backend'].ansible_host }}"
