---
POSTGRES_DB: mydatabase
POSTGRES_USER: postgres
POSTGRES_PASSWORD: password
POSTGRES_PORT: 5432
POSTGRES_HOST: "{{ hostvars[groups['tag_Name_databases'][0]].ansible_host }}"

REDIS_PORT: 6379
REDIS_HOST: "{{ hostvars[groups['tag_Name_databases'][0]].ansible_host }}"

MONGO_INITDB_DATABASE: schedules

SPRING_PROFILES_ACTIVE: prod
DATABASE_URL: jdbc:postgresql://"{{ hostvars['tag_Name_databases'].ansible_host }}":5432/mydatabase