apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  POSTGRES_DB: "database"
  POSTGRES_USER: "user"
  POSTGRES_PASSWORD: "password"
  POSTGRES_PORT: "5432"
  POSTGRES_HOST: "postgres"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dump-config
data:
  my.dump: |