---
postgres_user: "postgres"
postgres_database: "my_database"
postgres_port: 5432
postgres_password: "password"

mongo_initdb_database: "schedules"
redis_port: 6379

backend_ip: "{{ hostvars[groups['tag_Name_backend'][0]].ansible_host }}"
frontend_ip: "{{ hostvars[groups['tag_Name_frontend'][0]].ansible_host }}"

aws_access_key_id: "{{ aws_creds.aws_access_key_id }}"
aws_secret_access_key: "{{ aws_creds.aws_secret_access_key }}"
