apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: {{ .Values.services.backend.type }}
  ports:
    - port: {{ .Values.services.backend.port }}
      targetPort: {{ .Values.services.backend.targetPort }}
  selector:
    app: backend

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: {{ .Values.services.frontend.type }}
  ports:
    - port: {{ .Values.services.frontend.port }}
      targetPort: {{ .Values.services.frontend.targetPort }}
  selector:
    app: frontend

---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  type: {{ .Values.services.mongo.type }}
  selector:
    app: mongo
  ports:
    - port: {{ .Values.services.mongo.port }}       
      targetPort: {{ .Values.services.mongo.targetPort }}

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: {{ .Values.services.postgres.type }}
  selector:
    app: postgres
  ports:
    - port: {{ .Values.services.postgres.port }}        
      targetPort: {{ .Values.services.postgres.targetPort }}  

---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  type: {{ .Values.services.redis.type }}
  selector:
    app: redis
  ports:
    - port: {{ .Values.services.redis.port }}       
      targetPort: {{ .Values.services.redis.targetPort }}  

