apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
 
metadata:
  name: class-schedule-app
  version: 1.30
  region: eu-central-1
 
nodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 2
    privateNetworking: true
    ssh:
      publicKeyPath: /root/.ssh/id_rsa.pub

